### ISSUE TITLE
More/Assets is a required package for baseBox.lightBox

### ISSUE THREAD

**Issue by jarbor** [DimitarChristoff/baseBox#1]
Hi Dimitar,

Nice work with baseBox, keep up the good work. I just wanted to let you know that I ran into an issue when first installing baseBox with MooTools 1.3.2. I believe that More/Assets is a required package for baseBox.lightBox but you don't have it listed in the prerequisites. That is all; thanks again for the good work!
- Jeff Sneden

**Comment by DimitarChristoff** [comment]
cheers, done. I always saw the other class as the example on how to use baseBox and not as a class in its own right, really. other examples I have include baseBox.alert, baseBox.confirm etc.
