### ISSUE TITLE
options.scroll ineffective

### ISSUE THREAD

**Issue by leegee** [DimitarChristoff/baseBox#2]
Thank you for a superb modal box - lovely!

I am having problems with the scroll option for the body --- setting it to 'auto' does not have the expected effect of a scrollbar appearing. Setting it to 'scroll' does show the scroll bar, but it is much bigger than the body of the box.

Looking more carefully, it seems that the box body's height - as set by the options to the constructor - does not contain the content of the box. I see a dark background, but underneath, the text overflows.

Am I doing something wrong?

TIA
lee

**Comment by DimitarChristoff** [comment]
indeed, it would appear to be a regression as this worked until i refactored it to auto set height. will look into it asap.

**Comment by DimitarChristoff** [comment]
fixed. http://jsfiddle.net/dimitar/hrHdr/

**Comment by leegee** [comment]
```
Thanks!  That was fast.
  Is it me, or ...?  Please see image:
On 21/07/2011 10:46, DimitarChristoff wrote:

  fixed. http://jsfiddle.net/dimitar/hrHdr/
```
